document the current Multicore testsuite situation
ocamllabs/ocaml-multicore pull request #752
Opened 2021-11-22 10:48 UTC by gasche

(closes #751)

With this PR the documentation is up-to-date, and calling `make all` or `make parallel` shows an error message.

Note that `make all-foo` (which runs all tests starting with `foo`) is renamed to `make really-all-foo`. The `all-enabled` naming makes the previous pattern unfortunate anyway.

2021-11-29 14:43 UTC, Engil requested changes
Thank you for your PR!
This looks fine to me but is buggy at the moment because of a few typos. :)

I think though we should discuss how to address individually some of the outstanding issues.
Specifically the `parallel` target, which is hardly usable on Multicore because of the `parallel` testsuite.
Maybe the testsuite runner should be fed information about what tests directories are sequential and which one may execute multiple domains.
Going further, being able parametrize the multi-domains testcases would likely help as well relieve some pain in that area.

This is likely not the right place to discuss this, we should open a follow up issue after this one in order to make sure that we try to address a few of these at some point.

2021-11-29 14:43 UTC, Engil commented on testsuite/Makefile
> +.PHONY: paralell-%
A few of the same typos in the PR where `parallel` becomes `paralell`

2021-11-29 14:43 UTC, Engil commented on testsuite/Makefile
> +	@echo "'make paralell-*' targets are not supported on Multicore OCaml"
ditto

2021-11-29 14:43 UTC, Engil commented on testsuite/Makefile
> +.PHONY: paralell
ditto

2021-11-29 14:43 UTC, Engil commented on testsuite/Makefile
> +paralell:
Here as well

2021-11-29 15:14 UTC, gasche commented
Thanks for the feedback! I fixed the silly typos.

Re. `parallel`: a simple approach would to write a list of test directories that must not run in parallel, and have `make parallel` run only the other jobs in parallel, and those jobs in sequence after that (or before that). (The information could also be stored in each directory with more elaborate scripting.)

This being said, I think that the bigger-picture task is to cleanup the testsuite in the Multicore tree. If you want to start sending PRs to the upstream tree, you will need to send proper testsuite changes, and it's probably easier overall to work upfront to reduce the diff by cleaning up the testsuite in your tree.

2021-12-01 12:42 UTC, Engil approved these changes

2021-12-01 14:35 UTC, Engil commented
Thank you @gasche!

Agreed on having a way to distinguish sequential and parallel test directories. An alternative I'm thinking about could be to have a file (rather than storing information in individual directories) that describes what are the parallel test directories. (a bit like the `disabled` file in the Multicore tree handles disabled testcases.)
This would also lower the amount of scripting required.

I do agree the bigger picture involves some cleaning:
- A quick glance at the diff shows that some tests have non-required differences, I assume some changes that were lost in some of our rebases. These needs to be addressed.
- Do we want to keep the `disabled/enabled` mechanism? @ctk21 mentioned that the `skip` mechanism of `ocamltest` could be used instead of the disabled mechanism.
- @dra27 has some fixes for CI in #640 (I believe), including fixes for `parallel`. We should also integrate these.

Is there anything else that comes to your mind about the bigger picture for the testsuite story for 5.00?
Maybe we should devise proper RFCs to get a better view of the outstanding issues.

It does also seems that `CI` and `testsuite` are two separate concerns, and the the CI story for Multicore will need to be also a bit more clearly defined.
This stresses the previous point that we may want to submit a proposal/RFC for both CI and testsuite and make sure all concerns and outstanding issues are addressed and talked through properly.

2021-12-01 15:25 UTC, gasche commented
Note: I am not sure that you actually *need* specific care to avoid running certain tests in parallel. There are stress-tests that spawn multiple domains, but what if two of those tests run in parallel? At worst you are going to see less-deterministic scheduling, but that doesn't sound bad for testing, in fact possibly a plus. So I would first try to get `make parallel` to work on the Multicore tree (without forcing specific tests to be run alone), and see what happens.

> Do we want to keep the disabled/enabled mechanism?

It looks like a hack to me that you want to remove in favor of some upstream-supported way of skipping, indeed. 

If for some reason you found ocamltest not expressive enough for some testsuite features you would need, we can always improve ocamltest -- I would recommend opening an upstream issue, or hacking on ocamltest directly in the multicore repo if you feel like it.

> @dra27 has some fixes for CI in GitHub Actions for Windows #640 (I believe), including fixes for parallel. We should also integrate these.

Yes, I recommend integrating every @dra27 proposes for the testsuite :-) (And the present PR!)

> Is there anything else that comes to your mind about the bigger picture for the testsuite story for 5.00?

I think that the best would be for the multicore-ocaml testsuite to have a reasonable diff wrt. the trunk/4.14 testsuite by the time of the Multicore Merge, rather than 5.00. If you wait for later, potential problems include:
- if the Merge preserves the trunk testsuite, the tests may break due to tests you haven't seen in the multicore tree (we might even miss bugs if we promote test outputs without being careful)
- if the Merge does not include Multicore-specific tests, we end up with much weaker testsuite coverage of the concurrency features
- if the Merge moves the needle in the other direction of replacing the trunk testsuite by the multicore testsuite, we end up in a semi-broken testsuite state and developers/contributors/maintainers are going to complain (rightfully).

2021-12-01 17:08 UTC, ctk21 commented
> > Do we want to keep the disabled/enabled mechanism?
> 
> It looks like a hack to me that you want to remove in favor of some upstream-supported way of skipping, indeed.
> 
> If for some reason you found ocamltest not expressive enough for some testsuite features you would need, we can always improve ocamltest -- I would recommend opening an upstream issue, or hacking on ocamltest directly in the multicore repo if you feel like it.
> 

Multicore introduced `testsuite/disabled` probably before ocamltest existed. Over time the number of tests needing to be disabled has fallen, hopefully it will fall further. 

My take is: ocamltest now has the `skip` feature and we should use it and remove the `testsuite/disabled` file.

2021-12-01 17:16 UTC, gasche commented
I was curious, so I checked: indeed the first ocamltest commit was in July 2017 ( 635b5edcc1a0ce40d974295a696fbb3dea2f0766 ), while `testsuite/disabled` was added in March 2017 ( 1148920a8ad8cae9f06e5d5d1c778a43584f3440 ) :-)

2021-12-08 03:33 UTC, kayceesrk commented
We now have https://github.com/ocaml-multicore/ocaml-multicore/pull/774 which uses ocamltest `skip` mechanism. @moyodiallo confirmed that `make parallel` also works.

2021-12-10 16:27 UTC, ctk21 commented
I'm closing this PR, because the multicore testsuite now runs in the same way as the ocaml/ocaml.

2021-12-10 16:27 UTC, closed without merging